apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
data:
  stub_status.conf: |
    server {
      listen       80;
      server_name  localhost;
      location /basic_status {
        stub_status;
      }
    }